#ifndef TRAFFIC_SERVER_EXCEPTION_H
#define TRAFFIC_SERVER_EXCEPTION_H

enum error_codes
{
    EC_OK = 0,
    EC_NOT_ENOUGH_ARGS = 2,
#define POSIX_ERROR (-1)
    EC_CANT_CREATE_SOCKET = POSIX_ERROR,
    EC_CANT_BIND_SOCKET = POSIX_ERROR,
    EC_CANT_LISTEN_SOCKET = POSIX_ERROR,
    EC_CANT_ACCEPT_SOCKET = POSIX_ERROR,
    EC_CANT_READ_DATA = POSIX_ERROR,
    EC_CANT_SEND_DATA = POSIX_ERROR,
};

#endif //TRAFFIC_SERVER_EXCEPTION_H
